development:
  adapter: postgresql
  encoding: unicode
  database: formbuilder
  pool: 5
  username: vagrant
  password: hDprK5pvXp6FavcAn6c4jUpGXScSK5SrfBFYxU2mrPuwZ2tjQfx9HA7pMuULDA78TjWAKcR7

test:
  adapter: postgresql
  encoding: unicode
  database: formbuilder_test
  pool: 5
  username: vagrant
  password: hDprK5pvXp6FavcAn6c4jUpGXScSK5SrfBFYxU2mrPuwZ2tjQfx9HA7pMuULDA78TjWAKcR7

production:
  adapter: postgresql
  encoding: unicode
  database: formbuilder
  pool: 5
  username: vagrant
  password: hDprK5pvXp6FavcAn6c4jUpGXScSK5SrfBFYxU2mrPuwZ2tjQfx9HA7pMuULDA78TjWAKcR7
